name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_dev:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build_dev bild
      run: make ci-build-dev
    - name: build_dev up
      run: make up-d
    

      
  build_prod:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build_prod bild
      run: make ci-build-prod
    - name: build_dev up
      run: make prod
